version: '3.7'
services:
  jenkins:
    image: j2:v1
    environment:
      - TZ=Europe/Paris
      - JAVA_OPTS= "-Djava.awt.headless=true"
      - JAVA_OPTS= "-Djenkins.install.runSetupWizard=false" # Start jenkins unlocked 
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
